platform :ios, '11.0'

target 'RocketChatViewController Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'DifferenceKit', :git => 'https://github.com/ra1028/DifferenceKit.git', :branch => 'v0.5.3'

end
