platform :ios, '11.4'

target 'RocketChatViewController Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IGListKit/Diffing', '~> 3.0'

end
